### ISSUE TITLE
What is the convensional phoneme vocabulary for english?

### ISSUE THREAD

**Issue by Wonder1905** [ASR-project/Multilingual-PR#3]
Hi, I'm trying to use your code, I tried "en" option, I got and empty dict, then I saw that you
[ don't have an "en" dictionary avalible](https://github.com/ASR-project/Multilingual-PR#books-languages-for-which-phoneme-dictionaries-are-available). How can I get a decent phoneme-dictionary for English?

Thanks for your help!

**Comment by younesbelkada** [comment]
Hi @BattashB 
Thanks for your message!
I don't remember exactly the reasons behind that but I think that it is mainly because en dictionary is not available in the mentioned repo. 
Tagging @clementapa  and @ArthurZucker  since I am not sure

**Comment by ArthurZucker** [comment]
Hey! Thanks for the issue, I am pretty sure we did not use any english datasets as they were too huge! 
I think you can find other dictionaries, which could work for `english` in `Phonemizer` library, example [here](https://as-ideas.github.io/DeepPhonemizer/)

**Comment by clementapa** [comment]
Hi! Download this file https://github.com/phoible/dev/blob/master/data/phoible.csv and put it on the repository 'assets' and retry. Let me know if it works !
